from setuptools import setup, find_packages

setup(
    name="bark_enhanced",
    version="0.1.0a",
    description="Bark text to audio model with focus around a serverless deployment model",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Suno Inc (original Bark), Count Floyd",
    author_email="hello@suno.ai",
    url="https://github.com/sean-bailey/bark-gui",
    license="MIT",
    python_requires=">=3.8",
    packages=find_packages(),
    install_requires=[
        "boto3",
        "encodec",
        "funcy",
        "huggingface-hub>=0.14.1",
        "numpy",
        "scipy",
        "tokenizers",
        "torch",
        "tqdm",
        "transformers",
    ],
    extras_require={
        "dev": [
            "bandit",
            "black",
            "codecov",
            "flake8",
            "hypothesis>=6.14,<7",
            "isort>=5.0.0,<6",
            "jupyter",
            "mypy",
            "nbconvert",
            "nbformat",
            "pydocstyle",
            "pylint",
            "pytest",
            "pytest-cov",
        ],
    },
    classifiers=[
        "License :: OSI Approved :: MIT License",
    ],
)
